name: Autopep8

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.x
      uses: actions/setup-python@v3
      with:
        python-version: "3.x"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip autopep8 
    - uses: actions/checkout@v4

    - name: autopep8
      run: |
        autopep8 --in-place --aggressive --aggressive hw2_debugging.py rand.py test.py

    - name: Check if updated
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
          commit_message: Auto updated traces
          commit_author: Author <actions@github.com>
          commit_user_name: github-actions-bot
          commit_user_email: github-actions-bot@github.com
