name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  type_check_pyright:
    name: Type Check with Pyright
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.x
      uses: actions/setup-python@v3
      with:
        python-version: "3.x"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip pyright
    - name: Run Pyright
      run: |
        pyright hw2_debugging.py rand.py >> post_traces/pyright_trace.txt

  lint_pyflakes:
    name: Lint with Pyflakes
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.x
      uses: actions/setup-python@v3
      with:
        python-version: "3.x"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip pyflakes
    - name: Run Pyflakes
      run: |
        pyflakes hw2_debugging.py rand.py >> post_traces/pyflakes_trace.txt

  format_autopep8:
    name: Format with autopep8
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.x
      uses: actions/setup-python@v3
      with:
        python-version: "3.x"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip autopep8
    - name: Format Code
      run: |
        autopep8 --in-place --aggressive --aggressive hw2_debugging.py rand.py
    - name: Check if updated
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
         commit_author: "${{ steps.import-gpg.outputs.name }} <${{ steps.import-gpg.outputs.email }}>"
         commit_user_name: ${{ steps.import-gpg.outputs.name }}
         commit_user_email: ${{ steps.import-gpg.outputs.email }}

  run_tests:
    name: Run Tests with pytest
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.x
      uses: actions/setup-python@v3
      with:
        python-version: "3.x"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip pytest
    - name: Run pytest
      run: |
        pytest test.py
