name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.x
      uses: actions/setup-python@v3
      with:
        python-version: "3.x"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip pyright autopep8 pytest flake8 genbadge
    - uses: actions/checkout@v4
    - name: Run Pyright
      run: |
        pyright hw2_debugging.py rand.py >> post_traces/pyright.txt

    - name: Run flake8
      run: |
        flake8 --exit-zero --verbose --tee --output-file post_traces/flake8.txt
        > flake8_badge.txt
        flake8 --exit-zero --statistics --tee --output-file flake8_badge.txt

    - name: Check if updated
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
          commit_message: Auto updated traces
          commit_author: Author <actions@github.com>
          commit_user_name: github-actions-bot
          commit_user_email: github-actions-bot@github.com
    
    - name: Create flake8 badge
      run: 
        genbadge flake8 -i - < flake8_badge.txt -o - > flake8_badge.svg

    - name: Format Code
      run: |
        autopep8 --in-place --aggressive --aggressive hw2_debugging.py rand.py test.py

    - name: Run pytest
      run: |
        pytest test.py
        
    - name: Check if updated
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
          commit_message: Auto updated traces
          commit_author: Author <actions@github.com>
          commit_user_name: github-actions-bot
          commit_user_email: github-actions-bot@github.com
